version: "3.8"
volumes:
  pg_data:

services:
  db:
    image: postgres:15.3-alpine
    container_name: marketplace-db-local
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      dockerfile: Dockerfile
    container_name: marketplace-backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --no-input --username admin --email admin@example.com &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db